# INTEL CONFIDENTIAL
#
# Copyright 2021-2021 Intel Corporation.
#
# This software and the related documents are Intel copyrighted materials, and your use of
# them is governed by the express license under which they were provided to you ("License").
# Unless the License provides otherwise, you may not use, modify, copy, publish, distribute,
# disclose or transmit this software or the related documents without Intel's prior written permission.
#
# This software and the related documents are provided as is, with no express or implied warranties,
# other than those that are expressly stated in the License.

image:
  edgedns:
    repository: edgednssvr
    tag: "1.0"
    pullPolicy: IfNotPresent
  cert_requester:
    repository: certrequester
    tag: "1.0"
    pullPolicy: IfNotPresent

service:
  name: edgedns

rbac:
  serviceaccount: edgedns
  serviceaccount_namespace: smartedge-system
  clusterrole: csr-requester
  clusterrolebinding: edgedns-csr-requester

name: edgedns

env_configmap: env-config
volumes:
  secret: ca-certrequester
  hostpath:
    edgednssvr: /home/edgednssvr
    configs: /home/configs
    certs: /home/certs

edgedns_parameters:
  log_level: info
  sys_log_addr: 

  server:
    addr: 
    port: 4204

  listener:
    addr: 0.0.0.0
    port: 53

  statsd:
    ip: 
    port: 0
    hbInterval: 60
  #IPs need to be of the format "10.0.0.0/8"
  trustedips: "192.171.0.0/16,6.6.6.0/24"
